# -*- coding: utf-8 -*-
"""keras_glass_tables_query.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N2MBLbRQ9abQswwf_IiDsYpFV_e7we-4
"""

from google.colab import drive

drive.mount("/content/gdrive")  
!pwd

# Commented out IPython magic to ensure Python compatibility.
#put your own path in google drive
# %cd "/content/gdrive/My Drive/Datasets/GlassTable"

from keras.preprocessing import image
from keras import models
import matplotlib.pyplot as plt
import numpy as np

model = models.load_model('vgg_glass_and_tables.h5')

#test_img = 'table_test_1.jpg'
test_img = 'glass_test_2.jpg'

img_path = 'glass_and_tables_small/query/'+test_img

img = image.load_img(img_path,target_size=(150,150))
img_tensor = image.img_to_array(img)
img_tensor = np.expand_dims(img_tensor,axis=0)
img_tensor /= 255. 

class_val = model.predict_classes(img_tensor)
conf = model.predict(img_tensor)

print("Class: %s \nconfidence: %s/1\n" % (class_val[0][0], conf[0][0]))
print("Class name:")

if class_val[0][0] == 0:
  print("Glasses")
else:
  print("Tables")

plt.imshow(img_tensor[0])
plt.show()