# -*- coding: utf-8 -*-
"""keras_glass_tables_create_data_set.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y41DDIRf9p2fa-CqEoht7-SXwfn_XApZ
"""

from google.colab import drive

drive.mount("/content/gdrive")  
!pwd

# Commented out IPython magic to ensure Python compatibility.
#put your own path in google drive
# %cd "/content/gdrive/My Drive/Datasets"

import os, shutil

# dataset was uncompressed
original_dataset_dir = '/content/gdrive/My Drive/Datasets/GlassTable/train'

# The directory where we will
# store our smaller dataset
base_dir = '/content/gdrive/My Drive/Datasets/GlassTable/glass_and_tables_small'
os.mkdir(base_dir)

train_dir = os.path.join(base_dir, 'train')
os.mkdir(train_dir)

validation_dir = os.path.join(base_dir, 'validation')
os.mkdir(validation_dir)

test_dir = os.path.join(base_dir, 'test')
os.mkdir(test_dir)

train_glasses_dir = os.path.join(train_dir, 'glasses')
os.mkdir(train_glasses_dir)

train_tables_dir = os.path.join(train_dir, 'tables')
os.mkdir(train_tables_dir)


validation_glasses_dir = os.path.join(validation_dir, 'glasses')
os.mkdir(validation_glasses_dir)

validation_tables_dir = os.path.join(validation_dir, 'tables')
os.mkdir(validation_tables_dir)


test_glasses_dir = os.path.join(test_dir, 'glasses')
os.mkdir(test_glasses_dir)

test_tables_dir = os.path.join(test_dir, 'tables')
os.mkdir(test_tables_dir)

fnames = ['glass_{}.jpg'.format(i) for i in range(1,1001)]
for fname in fnames:
  src = os.path.join(original_dataset_dir, fname)
  dst = os.path.join(train_glasses_dir, fname)
  shutil.copyfile(src, dst)
  

fnames = ['glass_{}.jpg'.format(i) for i in range(1001, 1501)]
for fname in fnames:
  src = os.path.join(original_dataset_dir, fname)
  dst = os.path.join(validation_glasses_dir, fname)
  shutil.copyfile(src, dst)

  
fnames = ['glass_{}.jpg'.format(i) for i in range(1501, 2001)]
for fname in fnames:
  src = os.path.join(original_dataset_dir, fname)
  dst = os.path.join(test_glasses_dir, fname)
  shutil.copyfile(src, dst)

fnames = ['table_{}.jpg'.format(i) for i in range(1,1001)]
for fname in fnames:
  src = os.path.join(original_dataset_dir, fname)
  dst = os.path.join(train_tables_dir, fname)
  shutil.copyfile(src, dst)

fnames = ['table_{}.jpg'.format(i) for i in range(1001, 1501)]
for fname in fnames:
  src = os.path.join(original_dataset_dir, fname)
  dst = os.path.join(validation_tables_dir, fname)
  shutil.copyfile(src, dst)

fnames = ['table_{}.jpg'.format(i) for i in range(1501, 2001)]
for fname in fnames:
  src = os.path.join(original_dataset_dir, fname)
  dst = os.path.join(test_tables_dir, fname)
  shutil.copyfile(src, dst)